suwaki/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('suwaki.views',
    url(r'^$', 'home', name='home_page'),
    url(r'^get_news/$', 'news', name='suwaki_news'),
)

suwakiorg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import suwaki.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^suwakiorg/', include('suwakiorg.foo.urls')),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
) + suwaki.urls.urlpatterns

urlpatterns += staticfiles_urlpatterns()

suwaki/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Slider(models.Model):
    name = models.CharField(_('name'), max_length=255)
    ordering = models.IntegerField(_('ordering'))

    class Meta:
        verbose_name = _('slider')
        verbose_name_plural = _('sliders')
        ordering = ['ordering']

    def __unicode__(self):
        return self.name


class Value(models.Model):
    slider = models.ForeignKey(Slider, verbose_name=_('slider'))
    name = models.CharField(_('name'), max_length=255)
    ordering = models.IntegerField(_('ordering'))

    class Meta:
        ordering = ['ordering']
        verbose_name = _('value')
        verbose_name_plural = _('values')

    def __unicode__(self):
        return "%s: %s" % (self.slider.name, self.name)


# Create your models here.
class News(models.Model):
    #flickr_img = models.CharField(_)
    value = models.ForeignKey(Value, verbose_name=_('value'))
    title = models.CharField(_('title'), max_length=255)
    text = models.TextField(_('text'))
    active = models.BooleanField(_('active'), default=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']
        verbose_name = _('news')
        verbose_name_plural = _('news')

    def __unicode__(self):
        return self.title

    def to_dict(self):
        return {'title': self.title,
                'text': self.text,
                }

apps/suwaki/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render
from suwaki.constants import dimensions, MAX_NEWS
from suwaki import api


def home(request):
    return render(request, "suwaki/home.html", {
        "dimensions": dimensions,
    })




def news(request):
    values = {}
    for dim in dimensions:
        try:
            val = int(request.GET[dim.slug])
        except KeyError:
            continue
        except ValueError:
            continue
        values[dim.slug] = val
    chosen = api.get_relevant_news(values)[:MAX_NEWS]
    response_data = [n.to_dict() for n in chosen]
    return HttpResponse(json.dumps(response_data), mimetype="application/json")

suwaki/views.py
import json
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render
from suwaki import api
from suwaki.models import Slider


def home(request):
    return render(request, "suwaki/home.html", {
        "sliders": Slider.objects.all(),
    })


def news(request):
    values = {}
    for dim in Slider.objects.all():
        try:
            val = int(request.GET[str(dim.pk)])
        except KeyError:
            continue
        except ValueError:
            continue
        values[dim.pk] = val
    chosen = api.get_relevant_news(values, settings.SUWAKI_MAX_NEWS)
    response_data = [n.to_dict() for n in chosen]
    return HttpResponse(json.dumps(response_data), mimetype="application/json")

apps/suwaki/templates/suwaki/home.html
{% extends "base.html" %}
{% load i18n %}
{% load suwaki_tags %}

{% block "title" %}Suwaki{% endblock %}

{% block "body" %}
<h1>{% trans "Moving the copyright sliders." %}</h1>

    <section id="sliders">
    {% for dim in dimensions %}
	   <div class="dimension">
	       <div class="name">{{ dim.name }}</div>
	       <div class="slider-area">
	       <div class="slider" data-dimslug="{{ dim.slug}}" data-initial='150'></div>
	       {% spaceless %}
	       <ul class="stops">
    	       {% for stop in dim.stops %}
    		      <li style="{% stop_pos forloop.counter dim.stops %}"><span>{{ stop }}</span></li>
	       	   {% endfor %}
		   </ul>
		   {% endspaceless %}
		   </div>
	   </div>
    </section>
	{% endfor %}

    <section id="headers-area">
    <p id="noheaders">{% trans "No matching news found." %}</p>
    <ul id="headers">
    </ul>
    </section>
    <p><a id='add-link' href="">{% trans "Add some news!" %}</a></p>
        
{% endblock %}

suwaki/templates/base.html
<!DOCTYPE HTML>
{% load compressed %}
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{% block "title" %}{% endblock %}</title>
    {% compressed_css 'all' %}
</head>

<body>
    <div id="body">
    {% block "body" %}{% endblock %}
    </div>


    <footer>
        
    </footer>
</body>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
{% compressed_js 'all' %}
</html>

suwaki/templates/suwaki/home.html
{% extends "base.html" %}
{% load i18n %}
{% load suwaki_tags %}

{% block "title" %}Suwaki{% endblock %}

{% block "body" %}
<h1>{% trans "Moving the copyright sliders." %}</h1>

    <section id="sliders">
    {% for s in sliders %}
	   <div class="dimension">
	       <div class="name">{{ s.name }}</div>
	       <div class="slider-area">
	       <div class="slider" data-slider="{{ s.pk }}"></div>
	       {% spaceless %}
	       <ul class="stops">
    	       {% for v in s.value_set.all %}
    		      <li data-pk="{{ v.pk }}" style="{% stop_pos forloop.counter s.value_set.all %}"><span>{{ v.name }}</span></li>
	       	   {% endfor %}
		   </ul>
		   {% endspaceless %}
		   </div>
	   </div>
    </section>
	{% endfor %}

    <section id="headers-area">
    <p id="noheaders">{% trans "No relevant news found." %}</p>
    <ul id="headers">
    </ul>
    </section>
    <!--p><a id='add-link' href="">{% trans "Add some news!" %}</a></p-->
        
{% endblock %}